version: '3.7'
services:
  api:
    build: .
    ports:
        - '3000:3000'

  postgres:
      image: postgres:15.3
      restart: always
      environment: 
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=0123456
      logging:
        options:
          max-size: 10m
          max-file: "3"
      ports:
        - '5432:5432'
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
        # copy the sql script to create tables
        - ./sql/devops.sql:/docker-entrypoint-initdb.d/create_tables.sql
        